import { Image, type ImageProps } from 'expo-image';

const assets: Record<string, Record<string, number>> = {
  '34:10': {
    imgBookOpen: require('../../assets/images/latest-figma/34-10-imgBookOpen.svg') as number,
    imgCheckCircle2: require('../../assets/images/latest-figma/34-10-imgCheckCircle2.svg') as number,
    imgBookOpen1: require('../../assets/images/latest-figma/34-10-imgBookOpen1.svg') as number,
    imgDownload: require('../../assets/images/latest-figma/34-10-imgDownload.svg') as number,
    imgBookOpen2: require('../../assets/images/latest-figma/34-10-imgBookOpen2.svg') as number,
    imgBookOpen3: require('../../assets/images/latest-figma/34-10-imgBookOpen3.svg') as number,
    imgDownload1: require('../../assets/images/latest-figma/34-10-imgDownload1.svg') as number,
    imgMenu: require('../../assets/images/latest-figma/34-10-imgMenu.svg') as number,
    imgBookOpen4: require('../../assets/images/latest-figma/34-10-imgBookOpen4.svg') as number,
    imgTrophy: require('../../assets/images/latest-figma/34-10-imgTrophy.svg') as number,
    imgSparkles: require('../../assets/images/latest-figma/34-10-imgSparkles.svg') as number,
    imgTrendingUp: require('../../assets/images/latest-figma/34-10-imgTrendingUp.svg') as number,
    imgGift: require('../../assets/images/latest-figma/34-10-imgGift.svg') as number,
  },
  '255:6': {
    imgRefreshCw: require('../../assets/images/latest-figma/255-6-imgRefreshCw.svg') as number,
    imgBookOpen: require('../../assets/images/latest-figma/255-6-imgBookOpen.svg') as number,
    imgCheckCircle2: require('../../assets/images/latest-figma/255-6-imgCheckCircle2.svg') as number,
    imgBookOpen1: require('../../assets/images/latest-figma/255-6-imgBookOpen1.svg') as number,
    imgDownload: require('../../assets/images/latest-figma/255-6-imgDownload.svg') as number,
    imgBookOpen2: require('../../assets/images/latest-figma/255-6-imgBookOpen2.svg') as number,
    imgBookOpen3: require('../../assets/images/latest-figma/255-6-imgBookOpen3.svg') as number,
    imgDownload1: require('../../assets/images/latest-figma/255-6-imgDownload1.svg') as number,
    imgWifiOff1: require('../../assets/images/latest-figma/255-6-imgWifiOff1.svg') as number,
    imgMenu: require('../../assets/images/latest-figma/255-6-imgMenu.svg') as number,
    imgBookOpen4: require('../../assets/images/latest-figma/255-6-imgBookOpen4.svg') as number,
    imgTrophy: require('../../assets/images/latest-figma/255-6-imgTrophy.svg') as number,
    imgSparkles: require('../../assets/images/latest-figma/255-6-imgSparkles.svg') as number,
    imgTrendingUp: require('../../assets/images/latest-figma/255-6-imgTrendingUp.svg') as number,
    imgGift: require('../../assets/images/latest-figma/255-6-imgGift.svg') as number,
  },
  '34:893': {
    imgTrendingUp: require('../../assets/images/latest-figma/34-893-imgTrendingUp.svg') as number,
    imgFlame: require('../../assets/images/latest-figma/34-893-imgFlame.svg') as number,
    imgFlame1: require('../../assets/images/latest-figma/34-893-imgFlame1.svg') as number,
    imgChevronRight: require('../../assets/images/latest-figma/34-893-imgChevronRight.svg') as number,
    imgTrophy: require('../../assets/images/latest-figma/34-893-imgTrophy.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/34-893-imgFrame.svg') as number,
    imgGift: require('../../assets/images/latest-figma/34-893-imgGift.svg') as number,
    imgMenu: require('../../assets/images/latest-figma/34-893-imgMenu.svg') as number,
    imgBookOpen: require('../../assets/images/latest-figma/34-893-imgBookOpen.svg') as number,
    imgTrophy1: require('../../assets/images/latest-figma/34-893-imgTrophy1.svg') as number,
    imgSparkles: require('../../assets/images/latest-figma/34-893-imgSparkles.svg') as number,
    imgTrendingUp1: require('../../assets/images/latest-figma/34-893-imgTrendingUp1.svg') as number,
    imgGift1: require('../../assets/images/latest-figma/34-893-imgGift1.svg') as number,
  },
  '255:481': {
    imgTrendingUp: require('../../assets/images/latest-figma/255-481-imgTrendingUp.svg') as number,
    imgFlame: require('../../assets/images/latest-figma/255-481-imgFlame.svg') as number,
    imgFlame1: require('../../assets/images/latest-figma/255-481-imgFlame1.svg') as number,
    imgChevronRight: require('../../assets/images/latest-figma/255-481-imgChevronRight.svg') as number,
    imgTrophy: require('../../assets/images/latest-figma/255-481-imgTrophy.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/255-481-imgFrame.svg') as number,
    imgGift: require('../../assets/images/latest-figma/255-481-imgGift.svg') as number,
    imgMenu: require('../../assets/images/latest-figma/255-481-imgMenu.svg') as number,
    imgBookOpen: require('../../assets/images/latest-figma/255-481-imgBookOpen.svg') as number,
    imgTrophy1: require('../../assets/images/latest-figma/255-481-imgTrophy1.svg') as number,
    imgSparkles: require('../../assets/images/latest-figma/255-481-imgSparkles.svg') as number,
    imgTrendingUp1: require('../../assets/images/latest-figma/255-481-imgTrendingUp1.svg') as number,
    imgGift1: require('../../assets/images/latest-figma/255-481-imgGift1.svg') as number,
  },
  '34:279': {
    imgShield: require('../../assets/images/latest-figma/34-279-imgShield.svg') as number,
    imgShield1: require('../../assets/images/latest-figma/34-279-imgShield1.svg') as number,
    imgShield2: require('../../assets/images/latest-figma/34-279-imgShield2.svg') as number,
    imgTrendingUp: require('../../assets/images/latest-figma/34-279-imgTrendingUp.svg') as number,
    imgTrophy: require('../../assets/images/latest-figma/34-279-imgTrophy.svg') as number,
    imgMenu: require('../../assets/images/latest-figma/34-279-imgMenu.svg') as number,
    imgBookOpen: require('../../assets/images/latest-figma/34-279-imgBookOpen.svg') as number,
    imgTrophy1: require('../../assets/images/latest-figma/34-279-imgTrophy1.svg') as number,
    imgSparkles: require('../../assets/images/latest-figma/34-279-imgSparkles.svg') as number,
    imgTrendingUp1: require('../../assets/images/latest-figma/34-279-imgTrendingUp1.svg') as number,
    imgGift: require('../../assets/images/latest-figma/34-279-imgGift.svg') as number,
  },
  '34:585': {
    imgScanLine: require('../../assets/images/latest-figma/34-585-imgScanLine.svg') as number,
    imgSparkles: require('../../assets/images/latest-figma/34-585-imgSparkles.svg') as number,
    imgCheckCircle2: require('../../assets/images/latest-figma/34-585-imgCheckCircle2.svg') as number,
    imgAlertTriangle: require('../../assets/images/latest-figma/34-585-imgAlertTriangle.svg') as number,
    imgMic: require('../../assets/images/latest-figma/34-585-imgMic.svg') as number,
    imgScanLine1: require('../../assets/images/latest-figma/34-585-imgScanLine1.svg') as number,
    imgBookOpen: require('../../assets/images/latest-figma/34-585-imgBookOpen.svg') as number,
    imgLanguages: require('../../assets/images/latest-figma/34-585-imgLanguages.svg') as number,
    imgMic1: require('../../assets/images/latest-figma/34-585-imgMic1.svg') as number,
    imgSendHorizontal: require('../../assets/images/latest-figma/34-585-imgSendHorizontal.svg') as number,
    imgMenu: require('../../assets/images/latest-figma/34-585-imgMenu.svg') as number,
    imgBookOpen1: require('../../assets/images/latest-figma/34-585-imgBookOpen1.svg') as number,
    imgTrophy: require('../../assets/images/latest-figma/34-585-imgTrophy.svg') as number,
    imgSparkles1: require('../../assets/images/latest-figma/34-585-imgSparkles1.svg') as number,
    imgTrendingUp: require('../../assets/images/latest-figma/34-585-imgTrendingUp.svg') as number,
    imgGift: require('../../assets/images/latest-figma/34-585-imgGift.svg') as number,
  },
  '34:1192': {
    imgFlame: require('../../assets/images/latest-figma/34-1192-imgFlame.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/34-1192-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/34-1192-imgFrame1.svg') as number,
    imgBackpack: require('../../assets/images/latest-figma/34-1192-imgBackpack.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/34-1192-imgFrame2.svg') as number,
    imgSmartphone: require('../../assets/images/latest-figma/34-1192-imgSmartphone.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/34-1192-imgFrame3.svg') as number,
    imgMessageCircle: require('../../assets/images/latest-figma/34-1192-imgMessageCircle.svg') as number,
    imgChevronRight: require('../../assets/images/latest-figma/34-1192-imgChevronRight.svg') as number,
    imgUsers: require('../../assets/images/latest-figma/34-1192-imgUsers.svg') as number,
    imgPhoneCall: require('../../assets/images/latest-figma/34-1192-imgPhoneCall.svg') as number,
    imgMenu: require('../../assets/images/latest-figma/34-1192-imgMenu.svg') as number,
    imgBookOpen: require('../../assets/images/latest-figma/34-1192-imgBookOpen.svg') as number,
    imgTrophy: require('../../assets/images/latest-figma/34-1192-imgTrophy.svg') as number,
    imgSparkles: require('../../assets/images/latest-figma/34-1192-imgSparkles.svg') as number,
    imgTrendingUp: require('../../assets/images/latest-figma/34-1192-imgTrendingUp.svg') as number,
    imgGift: require('../../assets/images/latest-figma/34-1192-imgGift.svg') as number,
  },
  '139:3835': {
    imgEllipse: require('../../assets/images/latest-figma/139-3835-imgEllipse.svg') as number,
    imgEllipse1: require('../../assets/images/latest-figma/139-3835-imgEllipse1.svg') as number,
    imgEllipse2: require('../../assets/images/latest-figma/139-3835-imgEllipse2.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/139-3835-imgFrame.svg') as number,
    imgEllipse3: require('../../assets/images/latest-figma/139-3835-imgEllipse3.svg') as number,
    imgEllipse4: require('../../assets/images/latest-figma/139-3835-imgEllipse4.svg') as number,
    imgEllipse5: require('../../assets/images/latest-figma/139-3835-imgEllipse5.svg') as number,
    imgEllipse6: require('../../assets/images/latest-figma/139-3835-imgEllipse6.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/139-3835-imgFrame1.svg') as number,
  },
  '139:3836': {
    imgEllipse: require('../../assets/images/latest-figma/139-3836-imgEllipse.svg') as number,
    imgEllipse1: require('../../assets/images/latest-figma/139-3836-imgEllipse1.svg') as number,
    imgEllipse2: require('../../assets/images/latest-figma/139-3836-imgEllipse2.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/139-3836-imgFrame.svg') as number,
    imgEllipse3: require('../../assets/images/latest-figma/139-3836-imgEllipse3.svg') as number,
    imgEllipse4: require('../../assets/images/latest-figma/139-3836-imgEllipse4.svg') as number,
    imgEllipse5: require('../../assets/images/latest-figma/139-3836-imgEllipse5.svg') as number,
    imgEllipse6: require('../../assets/images/latest-figma/139-3836-imgEllipse6.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/139-3836-imgFrame1.svg') as number,
  },
  '139:3838': {
    imgEllipse: require('../../assets/images/latest-figma/139-3838-imgEllipse.svg') as number,
    imgEllipse1: require('../../assets/images/latest-figma/139-3838-imgEllipse1.svg') as number,
    imgEllipse2: require('../../assets/images/latest-figma/139-3838-imgEllipse2.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/139-3838-imgFrame.svg') as number,
    imgEllipse3: require('../../assets/images/latest-figma/139-3838-imgEllipse3.svg') as number,
    imgEllipse4: require('../../assets/images/latest-figma/139-3838-imgEllipse4.svg') as number,
    imgEllipse5: require('../../assets/images/latest-figma/139-3838-imgEllipse5.svg') as number,
    imgEllipse6: require('../../assets/images/latest-figma/139-3838-imgEllipse6.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/139-3838-imgFrame1.svg') as number,
  },
  '266:148': {
    imgEllipse: require('../../assets/images/latest-figma/266-148-imgEllipse.svg') as number,
    imgEllipse1: require('../../assets/images/latest-figma/266-148-imgEllipse1.svg') as number,
    imgEllipse2: require('../../assets/images/latest-figma/266-148-imgEllipse2.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/266-148-imgFrame.svg') as number,
    imgEllipse3: require('../../assets/images/latest-figma/266-148-imgEllipse3.svg') as number,
    imgEllipse4: require('../../assets/images/latest-figma/266-148-imgEllipse4.svg') as number,
    imgEllipse5: require('../../assets/images/latest-figma/266-148-imgEllipse5.svg') as number,
    imgEllipse6: require('../../assets/images/latest-figma/266-148-imgEllipse6.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/266-148-imgFrame1.svg') as number,
  },
  '266:188': {
    imgEllipse: require('../../assets/images/latest-figma/266-188-imgEllipse.svg') as number,
    imgEllipse1: require('../../assets/images/latest-figma/266-188-imgEllipse1.svg') as number,
    imgEllipse2: require('../../assets/images/latest-figma/266-188-imgEllipse2.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/266-188-imgFrame.svg') as number,
    imgEllipse3: require('../../assets/images/latest-figma/266-188-imgEllipse3.svg') as number,
    imgEllipse4: require('../../assets/images/latest-figma/266-188-imgEllipse4.svg') as number,
    imgEllipse5: require('../../assets/images/latest-figma/266-188-imgEllipse5.svg') as number,
    imgEllipse6: require('../../assets/images/latest-figma/266-188-imgEllipse6.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/266-188-imgFrame1.svg') as number,
  },
  '266:227': {
    imgEllipse: require('../../assets/images/latest-figma/266-227-imgEllipse.svg') as number,
    imgEllipse1: require('../../assets/images/latest-figma/266-227-imgEllipse1.svg') as number,
    imgEllipse2: require('../../assets/images/latest-figma/266-227-imgEllipse2.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/266-227-imgFrame.svg') as number,
    imgEllipse3: require('../../assets/images/latest-figma/266-227-imgEllipse3.svg') as number,
    imgEllipse4: require('../../assets/images/latest-figma/266-227-imgEllipse4.svg') as number,
    imgEllipse5: require('../../assets/images/latest-figma/266-227-imgEllipse5.svg') as number,
    imgEllipse6: require('../../assets/images/latest-figma/266-227-imgEllipse6.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/266-227-imgFrame1.svg') as number,
  },
  '277:10': {
    imgFrame: require('../../assets/images/latest-figma/277-10-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-10-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-10-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-10-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-10-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-10-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-10-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-10-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-10-imgFrame8.svg') as number,
  },
  '277:73': {
    imgFrame: require('../../assets/images/latest-figma/277-73-imgFrame.svg') as number,
    imgEllipse: require('../../assets/images/latest-figma/277-73-imgEllipse.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-73-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-73-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-73-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-73-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-73-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-73-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-73-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-73-imgFrame8.svg') as number,
    imgFrame9: require('../../assets/images/latest-figma/277-73-imgFrame9.svg') as number,
    imgFrame10: require('../../assets/images/latest-figma/277-73-imgFrame10.svg') as number,
  },
  '277:136': {
    imgFrame: require('../../assets/images/latest-figma/277-136-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-136-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-136-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-136-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-136-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-136-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-136-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-136-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-136-imgFrame8.svg') as number,
  },
  '277:199': {
    imgFrame: require('../../assets/images/latest-figma/277-199-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-199-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-199-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-199-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-199-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-199-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-199-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-199-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-199-imgFrame8.svg') as number,
    imgFrame9: require('../../assets/images/latest-figma/277-199-imgFrame9.svg') as number,
  },
  '277:262': {
    imgFrame: require('../../assets/images/latest-figma/277-262-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-262-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-262-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-262-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-262-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-262-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-262-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-262-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-262-imgFrame8.svg') as number,
    imgFrame9: require('../../assets/images/latest-figma/277-262-imgFrame9.svg') as number,
    imgFrame10: require('../../assets/images/latest-figma/277-262-imgFrame10.svg') as number,
    imgFrame11: require('../../assets/images/latest-figma/277-262-imgFrame11.svg') as number,
    imgFrame12: require('../../assets/images/latest-figma/277-262-imgFrame12.svg') as number,
    imgFrame13: require('../../assets/images/latest-figma/277-262-imgFrame13.svg') as number,
  },
  '277:325': {
    imgFrame: require('../../assets/images/latest-figma/277-325-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-325-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-325-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-325-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-325-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-325-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-325-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-325-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-325-imgFrame8.svg') as number,
    imgFrame9: require('../../assets/images/latest-figma/277-325-imgFrame9.svg') as number,
    imgFrame10: require('../../assets/images/latest-figma/277-325-imgFrame10.svg') as number,
    imgFrame11: require('../../assets/images/latest-figma/277-325-imgFrame11.svg') as number,
    imgFrame12: require('../../assets/images/latest-figma/277-325-imgFrame12.svg') as number,
    imgFrame13: require('../../assets/images/latest-figma/277-325-imgFrame13.svg') as number,
  },
  '277:382': {
    imgFrame: require('../../assets/images/latest-figma/277-382-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-382-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-382-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-382-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-382-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-382-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-382-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-382-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-382-imgFrame8.svg') as number,
    imgFrame9: require('../../assets/images/latest-figma/277-382-imgFrame9.svg') as number,
    imgFrame10: require('../../assets/images/latest-figma/277-382-imgFrame10.svg') as number,
  },
  '277:439': {
    imgFrame: require('../../assets/images/latest-figma/277-439-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-439-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-439-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-439-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-439-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-439-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-439-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-439-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-439-imgFrame8.svg') as number,
    imgFrame9: require('../../assets/images/latest-figma/277-439-imgFrame9.svg') as number,
    imgFrame10: require('../../assets/images/latest-figma/277-439-imgFrame10.svg') as number,
  },
  '277:496': {
    imgFrame: require('../../assets/images/latest-figma/277-496-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-496-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-496-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-496-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-496-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-496-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-496-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-496-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-496-imgFrame8.svg') as number,
  },
  '277:553': {
    imgFrame: require('../../assets/images/latest-figma/277-553-imgFrame.svg') as number,
    imgEllipse: require('../../assets/images/latest-figma/277-553-imgEllipse.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/277-553-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/277-553-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/277-553-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/277-553-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/277-553-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/277-553-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/277-553-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/277-553-imgFrame8.svg') as number,
  },
  '139:2592': {
    imgRefreshCw: require('../../assets/images/latest-figma/139-2592-imgRefreshCw.svg') as number,
    imgBookOpen: require('../../assets/images/latest-figma/139-2592-imgBookOpen.svg') as number,
    imgCheckCircle2: require('../../assets/images/latest-figma/139-2592-imgCheckCircle2.svg') as number,
    imgBookOpen1: require('../../assets/images/latest-figma/139-2592-imgBookOpen1.svg') as number,
    imgDownload: require('../../assets/images/latest-figma/139-2592-imgDownload.svg') as number,
    imgBookOpen2: require('../../assets/images/latest-figma/139-2592-imgBookOpen2.svg') as number,
    imgBookOpen3: require('../../assets/images/latest-figma/139-2592-imgBookOpen3.svg') as number,
    imgDownload1: require('../../assets/images/latest-figma/139-2592-imgDownload1.svg') as number,
    imgWifiOff1: require('../../assets/images/latest-figma/139-2592-imgWifiOff1.svg') as number,
    imgMenu: require('../../assets/images/latest-figma/139-2592-imgMenu.svg') as number,
    imgBookOpen4: require('../../assets/images/latest-figma/139-2592-imgBookOpen4.svg') as number,
    imgTrophy: require('../../assets/images/latest-figma/139-2592-imgTrophy.svg') as number,
    imgSparkles: require('../../assets/images/latest-figma/139-2592-imgSparkles.svg') as number,
    imgTrendingUp: require('../../assets/images/latest-figma/139-2592-imgTrendingUp.svg') as number,
    imgGift: require('../../assets/images/latest-figma/139-2592-imgGift.svg') as number,
    imgFrame: require('../../assets/images/latest-figma/139-2592-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/139-2592-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/139-2592-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/139-2592-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/139-2592-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/139-2592-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/139-2592-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/139-2592-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/139-2592-imgFrame8.svg') as number,
    imgFrame9: require('../../assets/images/latest-figma/139-2592-imgFrame9.svg') as number,
    imgFrame10: require('../../assets/images/latest-figma/139-2592-imgFrame10.svg') as number,
  },
  '319:10': {
    imgFrame: require('../../assets/images/latest-figma/319-10-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/319-10-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/319-10-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/319-10-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/319-10-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/319-10-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/319-10-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/319-10-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/319-10-imgFrame8.svg') as number,
    imgFrame9: require('../../assets/images/latest-figma/319-10-imgFrame9.svg') as number,
    imgFrame10: require('../../assets/images/latest-figma/319-10-imgFrame10.svg') as number,
  },
  '321:10': {
    imgFrame: require('../../assets/images/latest-figma/321-10-imgFrame.svg') as number,
    imgFrame1: require('../../assets/images/latest-figma/321-10-imgFrame1.svg') as number,
    imgFrame2: require('../../assets/images/latest-figma/321-10-imgFrame2.svg') as number,
    imgFrame3: require('../../assets/images/latest-figma/321-10-imgFrame3.svg') as number,
    imgFrame4: require('../../assets/images/latest-figma/321-10-imgFrame4.svg') as number,
    imgFrame5: require('../../assets/images/latest-figma/321-10-imgFrame5.svg') as number,
    imgFrame6: require('../../assets/images/latest-figma/321-10-imgFrame6.svg') as number,
    imgFrame7: require('../../assets/images/latest-figma/321-10-imgFrame7.svg') as number,
    imgFrame8: require('../../assets/images/latest-figma/321-10-imgFrame8.svg') as number,
    imgFrame9: require('../../assets/images/latest-figma/321-10-imgFrame9.svg') as number,
    imgFrame10: require('../../assets/images/latest-figma/321-10-imgFrame10.svg') as number,
  },
};

/** Original, locally bundled SVG artwork from the live Figma frames. */
export function FigmaAsset({ frame, name, width, height, style }: { frame: string; name: string; width: number; height: number; style?: ImageProps['style'] }) {
  const source = assets[frame]?.[name];
  if (!source) return null;
  return <Image source={source} contentFit="contain" accessible={false} style={[{ width, height }, style]} />;
}

