#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Everything runs from the repository root, whatever directory you started in.
ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$ROOT"

# Generate a random secret: HEX_BYTES → hex string. Uses node, which this repo
# already requires.
_random_hex() { node -e "console.log(require('node:crypto').randomBytes($1).toString('hex'))"; }

banner "K-Go Quests: set up a fresh clone"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites and dependencies"
say "Checking the tools this repo needs, then installing workspace packages."
MISSING=""
for tool in node npm git; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "found $tool — $("$tool" --version 2>&1 | head -n1 || true)"
  else
    warn "MISSING: $tool"; MISSING="$MISSING $tool"
  fi
done
for tool in docker python gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "found $tool (optional)"
  else
    note "no $tool — optional, only some stages need it"
  fi
done
if [[ -n "$MISSING" ]]; then
  warn "install$MISSING first, then run this script again."
  exit 1
fi
say ""
say "Installing with npm workspaces from the repository root."
if confirm "Run 'npm ci' now? (skip if you have already installed)"; then
  npm ci || { warn "npm ci failed. Fix it, then re-run this script."; exit 1; }
else
  SKIPPED+=("npm ci at the repository root")
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
ENV_FILE="$ROOT/mobile/.env.local"

stage "Clerk: the Caretaker Account"
say "The Caretaker signs in once at Setup with an email code. That sign-in is"
say "Clerk, and the app needs its PUBLISHABLE key — never the secret key."
open_url "https://dashboard.clerk.com/"
step "Create a development instance, or open an existing one."
step "Turn on email-code sign-in. In the current dashboard this lives under"
note "  the instance's sign-in / authentication settings — enable 'Email' and"
note "  its verification CODE (not a magic link). The app sends a code and asks"
note "  the Caretaker to type it, so a link-only instance will not work."
step "Open the API keys page and copy the Publishable key (starts pk_test_)."
pause "Press Enter once you have the publishable key on your clipboard"
ask EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY "Paste the Clerk publishable key:"
if [[ "$EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY" != pk_* ]]; then
  warn "that does not start with 'pk_'. A secret key starts 'sk_' and must never"
  warn "go in the app or the repo. Check you copied the publishable one."
  confirm "Use it anyway?" || { warn "stopping so you can re-copy the key."; exit 1; }
fi
write_env EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY "$EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY"

# ── 3 ─────────────────────────────────────────────────────────────────────
ENV_FILE="$ROOT/backend/.env"

stage "The database: Aiven or local Docker"
say "The school server needs PostgreSQL. Two supported paths:"
step "aiven — a hosted Aiven service, which is what backend/README.md documents."
step "local — the Postgres 17 container in backend/docker-compose.yml."
say ""
note "Either way DATABASE_SCHEMA stays 'kgo', which isolates this backend from"
note "the public tables described in backend/docs/database.md."
say ""
DB_CHOICE=""
while [[ "$DB_CHOICE" != "aiven" && "$DB_CHOICE" != "local" ]]; do
  ask DB_CHOICE "Which one? [aiven/local]"
  DB_CHOICE=$(printf '%s' "$DB_CHOICE" | tr '[:upper:]' '[:lower:]')
done

if [[ "$DB_CHOICE" == "aiven" ]]; then
  open_url "https://console.aiven.io/"
  step "Open (or create) your PostgreSQL service and wait until it is running."
  step "From the service overview, copy the connection URI — the postgres:// one."
  note "  I have deliberately not written exact clicks here: the Aiven console"
  note "  changes, and a wrong click path is worse than none. The URI and the CA"
  note "  download both live on the service's connection information."
  ask_secret DATABASE_URL "Paste the Aiven connection URI:"
  say ""
  step "Download the project CA certificate and save it to:"
  note "  $ROOT/backend/certs/aiven-ca.pem"
  pause "Press Enter once the CA file is saved there"
  if [[ -f "$ROOT/backend/certs/aiven-ca.pem" ]]; then
    note "found certs/aiven-ca.pem"
  else
    warn "certs/aiven-ca.pem is not there yet. TLS verification is on, so the"
    warn "backend will refuse to connect without it."
    SKIPPED+=("save the Aiven project CA to backend/certs/aiven-ca.pem")
  fi
  write_env DATABASE_URL "$DATABASE_URL"
  write_env DATABASE_SSL "true"
  write_env DATABASE_CA_PATH "certs/aiven-ca.pem"
  warn "do not add sslmode or other SSL query parameters to DATABASE_URL:"
  warn "node-postgres can let them override the explicit TLS settings."
else
  say "Generating a password for the local container."
  POSTGRES_PASSWORD=$(_random_hex 18)
  note "generated a 36-character password"
  write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
  write_env DATABASE_URL "postgresql://kgo:${POSTGRES_PASSWORD}@localhost:5432/kgo"
  write_env DATABASE_SSL "false"
  write_env DATABASE_CA_PATH ""
  say ""
  if command -v docker >/dev/null 2>&1; then
    if confirm "Start the Postgres container now?"; then
      ( cd "$ROOT/backend" && docker compose up -d ) \
        || { warn "docker compose failed. Start it by hand in backend/, then continue."; SKIPPED+=("start the Postgres container in backend/"); }
    else
      SKIPPED+=("start the Postgres container: cd backend && docker compose up -d")
    fi
  else
    warn "docker is not installed, so the container cannot be started here."
    SKIPPED+=("install Docker, then: cd backend && docker compose up -d")
  fi
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Backend application secrets"
say "These are generated here, not fetched from anywhere. Nothing to copy."
JWT_SECRET=$(_random_hex 48)
note "generated JWT_SECRET (96 characters — the backend requires at least 48)"
BOOTSTRAP_PASSWORD=$(_random_hex 16)
note "generated BOOTSTRAP_PASSWORD for the first LGU admin"
DEMO_PASSWORD=$(_random_hex 16)
note "generated DEMO_PASSWORD for the optional demo accounts"
say ""
ask BOOTSTRAP_LOGIN "Login for the first LGU admin [admin-demo]:"
[[ -z "$BOOTSTRAP_LOGIN" ]] && BOOTSTRAP_LOGIN="admin-demo"
ask BOOTSTRAP_JURISDICTION "Name of its jurisdiction [Demo LGU]:"
[[ -z "$BOOTSTRAP_JURISDICTION" ]] && BOOTSTRAP_JURISDICTION="Demo LGU"

write_env NODE_ENV "development"
write_env PORT "3000"
write_env DATABASE_SCHEMA "kgo"
write_env JWT_SECRET "$JWT_SECRET"
write_env JWT_ISSUER "kgo-quests"
write_env CORS_ORIGINS "http://localhost:8081,http://localhost:19006"
write_env SWAGGER_ENABLED "true"
write_env TRUST_PROXY_HOPS "0"
write_env BOOTSTRAP_LOGIN "$BOOTSTRAP_LOGIN"
write_env BOOTSTRAP_PASSWORD "$BOOTSTRAP_PASSWORD"
write_env BOOTSTRAP_JURISDICTION "$BOOTSTRAP_JURISDICTION"
write_env DEMO_PASSWORD "$DEMO_PASSWORD"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the schema"
say "This creates schema 'kgo' and applies migrations under a deployment lock."
warn "It writes to the database you configured in stage 3. Do not point it at"
warn "a database holding anything you care about."
say ""
if confirm "Run 'npm run db:migrate' now?"; then
  ( cd "$ROOT/backend" && npm run db:migrate ) \
    || { warn "db:migrate failed. Check DATABASE_URL and that the server is reachable."; SKIPPED+=("cd backend && npm run db:migrate"); }
  say ""
  say "Verifying the schema is complete."
  ( cd "$ROOT/backend" && npm run db:check ) \
    || warn "db:check did not report ready. /api/v1/health/ready will return 503 until it does."
else
  SKIPPED+=("cd backend && npm run db:migrate")
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Create the first LGU admin"
say "Bootstrap runs once, from the CLI, never from an HTTP endpoint. It creates"
say "a real administrator account using BOOTSTRAP_LOGIN and BOOTSTRAP_PASSWORD."
say ""
if confirm "Run 'npm run db:bootstrap' now?"; then
  ( cd "$ROOT/backend" && npm run db:bootstrap ) \
    || { warn "db:bootstrap failed. It needs the schema from stage 5."; SKIPPED+=("cd backend && npm run db:bootstrap"); }
  say ""
  warn "backend/README.md says to remove BOOTSTRAP_PASSWORD from the environment"
  warn "once provisioning has succeeded. Note the password somewhere safe first:"
  warn "it is in backend/.env and this script will not print it."
  SKIPPED+=("remove BOOTSTRAP_PASSWORD from backend/.env once you have saved it")
else
  SKIPPED+=("cd backend && npm run db:bootstrap")
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Optional: demo data"
say "Creates student-demo, teacher-demo, a Grade 5 Classroom, three fraction"
say "questions and one reward, using DEMO_PASSWORD."
note "These are demo records, not real Learner data. Skip this for a real"
note "deployment."
say ""
if confirm "Run 'npm run db:seed' now?"; then
  ( cd "$ROOT/backend" && npm run db:seed ) \
    || { warn "db:seed failed."; SKIPPED+=("cd backend && npm run db:seed"); }
else
  note "skipped. 'npm run smoke:configured' in stage 9 needs this seed."
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
ENV_FILE="$ROOT/ml/.env"

stage "The ML service"
say "The parameter-fitting service reads the SAME database as the backend, in"
say "the SAME schema — so these two values must match what you set in stage 3."
say ""
KGO_ML_TOKEN=$(_random_hex 24)
note "generated KGO_ML_TOKEN (48 characters — settings.py requires at least 24)"
write_env KGO_ML_TOKEN "$KGO_ML_TOKEN"

# Guarded: grep exits 1 when the key is absent, and pipefail would end the run.
BACKEND_URL=$( { grep -E '^DATABASE_URL=' "$ROOT/backend/.env" 2>/dev/null || true; } | tail -n1 | cut -d= -f2- || true)
if [[ -n "$BACKEND_URL" ]]; then
  if confirm "Reuse the DATABASE_URL already in backend/.env?"; then
    write_env DATABASE_URL "$BACKEND_URL"
  else
    ask_secret DATABASE_URL "Paste the connection URI for the ML service:"
    write_env DATABASE_URL "$DATABASE_URL"
  fi
else
  ask_secret DATABASE_URL "Paste the connection URI for the ML service:"
  write_env DATABASE_URL "$DATABASE_URL"
fi
write_env DATABASE_SCHEMA "kgo"
say ""
warn "two processes now write this one schema: the backend and the ML service."
warn "That is by design, and backend/docs/ml-contract.md is where the boundary"
warn "between them belongs."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Running the checks that prove this clone works."
say ""
say "Mobile tests:"
( cd "$ROOT/mobile" && npm test ) || warn "mobile tests failed"
say ""
if confirm "Also run the backend's configured-database smoke test? (needs stages 6 and 7)"; then
  ( cd "$ROOT/backend" && npm run smoke:configured ) \
    || warn "smoke:configured failed. It needs both the bootstrap admin and the demo seed."
fi
say ""
say "To run the app:"
note "  cd mobile && npx expo start     # press a for Android"
say "To run the school server:"
note "  cd backend && npm run start:dev"
say ""
note "The app works with no network at all. Online Mode is an accelerator:"
note "see docs/online-mode.md."

finish
